# Generated by Django 5.2.12 on 2026-04-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linked_farmer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
