# Generated by Django 5.2.12 on 2026-04-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_voice_note_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linked_farmer_id',
        ),
    ]
