# Generated by Django 5.2.13 on 2026-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_farmer_id_remove_user_linked_farmer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='produce_type',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
