# Generated by Django 5.2.13 on 2026-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_produce_type_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Buyer', 'Buyer'), ('Admin', 'Admin')], default='Buyer', max_length=10),
        ),
    ]
